name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: Heroku
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_email: "mail@rickvanloon.nl"
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "rickvanloon-p4"